services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
      - API_BASE_URL=http://api:8000
    depends_on:
      - api
  db:
    image: postgres
    platform: linux/amd64
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  api:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: app/Dockerfile
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --reload'
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - '8000:8000'
volumes:
  postgres_data:
